services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, :80}
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      DB_CONNECTION: pgsql
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB:-relaxpp}
      DB_USERNAME: ${POSTGRES_USER:-relaxpp}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER:-relaxpp}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-!ChangeMe!}
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: udp
    volumes:
      - ./api:/app
      - /app/vendor
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
      - rabbitmq
      - redis
    restart: unless-stopped

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-relaxpp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-relaxpp}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    restart: unless-stopped
  
  redis:
    image: redis:${REDIS_VERSION:-8}-alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
  
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4.3}-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "relaxpp"
      RABBITMQ_DEFAULT_PASS: "!ChangeMe!"
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped


volumes:
  database_data:
  redis_data:
  rabbitmq_data:
  caddy_data:
  caddy_config:
